#pragma once
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <initializer_list>

namespace picture {
constexpr size_t width = 400, height = 600, headerSize = 16;
constexpr size_t fileSize = headerSize + width * height / 2;
constexpr uint8_t header[headerSize] = {'P','6','I','1',0x90,1,0x58,2,0,0,0,0,0,0,0,0};
constexpr size_t thumbWidth=80,thumbHeight=120,thumbSize=headerSize+thumbWidth*thumbHeight/2;
// Caller validates source. Sample centres of 5x5 blocks in the stored orientation.
inline void thumbnail(const uint8_t* source,uint8_t* target){
    const uint8_t h[16]={'P','6','T','1',80,0,120,0,0,0,0,0,0,0,0,0};
    memcpy(target,h,16);memset(target+16,0,thumbSize-16);
    for(size_t y=0;y<thumbHeight;++y)for(size_t x=0;x<thumbWidth;++x){
        size_t i=(y*5+2)*width+x*5+2,j=y*thumbWidth+x;
        uint8_t b=source[16+i/2],c=(i&1)?b&15:b>>4;
        target[16+j/2]|=c<<((j&1)?0:4);
    }
}
// Palette indices: black, white, yellow, red, blue, green. High nibble first.
inline bool valid(const uint8_t* bytes, size_t size) {
    if (!bytes || size != fileSize || memcmp(bytes, header, headerSize)) return false;
    for (size_t i = headerSize; i < size; ++i)
        if ((bytes[i] >> 4) > 5 || (bytes[i] & 15) > 5) return false;
    return true;
}
inline bool month(const char* s) {
    if (strlen(s) != 7 || s[4] != '-') return false;
    for (int i : {0,1,2,3,5,6}) if (s[i] < '0' || s[i] > '9') return false;
    int m = (s[5]-'0')*10+s[6]-'0';
    return s[0] == '2' && m >= 1 && m <= 12;
}
inline bool date(const char* s) {
    if (strlen(s) != 15 || s[8] != '_') return false;
    for (int i = 0; i < 15; ++i) if (i != 8 && (s[i] < '0' || s[i] > '9')) return false;
    auto n = [s](int i) { return (s[i]-'0')*10+s[i+1]-'0'; };
    int y = n(0)*100+n(2), m = n(4), d = n(6);
    const int days[] = {0,31,28,31,30,31,30,31,31,30,31,30,31};
    if (y < 2000 || y > 2999 || m < 1 || m > 12) return false;
    int maxDay = days[m] + (m == 2 && y%4 == 0 && (y%100 != 0 || y%400 == 0));
    return d >= 1 && d <= maxDay && n(9) < 24 && n(11) < 60 && n(13) < 60;
}
// Only paths generated by this application can be displayed through HTTP.
inline bool orientation(const char* s) { return s && strlen(s)==1 && (s[0]=='p'||s[0]=='l'); }
inline bool path(const char* s) {
    if (!s) return false;
    size_t length=strlen(s);
    if ((length!=45 && length!=47) || strncmp(s, "/pictures/", 10) || s[14] != '/' || s[17] != '/' ||
        s[33] != '_') return false;
    size_t randomStart=34;
    if(length==47){if((s[34]!='p'&&s[34]!='l')||s[35]!='_')return false;randomStart=36;}
    if(strcmp(s+randomStart+8,".p6"))return false;
    char stamp[16]; memcpy(stamp, s+18, 15); stamp[15] = 0;
    if (!date(stamp) || memcmp(s+10, stamp, 4) || memcmp(s+15, stamp+4, 2)) return false;
    for (size_t i=randomStart;i<randomStart+8;++i) if (!((s[i]>='0' && s[i]<='9') || (s[i]>='a' && s[i]<='f'))) return false;
    return true;
}
}
