#pragma once
constexpr char REFRESH_TEST_HTML[] = R"HTML(<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="paper-token" content="{{TOKEN}}"><title>Paper OS · Refresh experiment</title><style>
body{font:18px system-ui;background:#f4f1e8;color:#19231e;max-width:720px;margin:auto;padding:24px}button,select{font:inherit;padding:10px;margin:8px 8px 8px 0;max-width:100%}label{display:block}pre{white-space:pre-wrap}a{color:#195d3b}
</style><a href="/device">Device lab</a> / <a href="/books">Books</a><h1>Refresh timing experiment</h1>
<p>This is an experimental <strong>full-screen</strong> refresh, not a partial update. It changes the panel clock for one chart only. Normal timing is restored after completion; nothing is enabled permanently.</p>
<p>USB power is recommended for consistent comparisons, not required: a sufficiently charged battery is accepted. Keep the device powered, at room temperature, and do not press power/reset while it refreshes. Image quality and long-term behaviour at the experimental timing are unverified.</p>
<ol><li>Choose a pattern and variant; run it at normal timing once after each reboot.</li><li>Tick the acknowledgement, then run one accelerated page. Compare the same pattern/variant at normal and accelerated timing.</li><li>Try serif variant 1 then 2, inverse text, checkerboard variants, colour variants, then white cleanup. Inspect after each completed refresh for old letters, squares or colour residue.</li><li>If output looks poor, use normal timing for cleanup. Return to Books to continue reading at normal timing.</li></ol>
<p>The physical A/B/C buttons leave the test page for reader controls; they do not select tests. Use these browser controls. Every click runs just one full-screen refresh; there is no automatic loop.</p>
<label>Pattern <select id="pattern"><option value="chart">Comparison chart</option><option value="serif">Full page · Book Serif 12 pt</option><option value="sans">Full page · Clean Sans 12 pt</option><option value="inverse">White text on black</option><option value="checker">Black/white checkerboard</option><option value="colour">Six-colour blocks</option><option value="white">White cleanup</option></select></label>
<label>Variant <select id="variant"><option value="1">1</option><option value="2">2 · alternate text / shifted pattern</option></select></label>
<label><input id="ack" type="checkbox"> I understand this changes panel timing experimentally.</label><p><button id="normal">Normal timing (one page)</button><button id="fast" disabled>Accelerated timing (one page)</button></p>
<h2>Recent completed tests</h2><pre id="history">None this boot.</pre><p>Last eight tests, held in RAM. Compare like-for-like patterns; the last normal/accelerated totals below may be for different pages.</p>
<pre id="state">Checking device…</pre><p id="message" role="status"></p><p>If a timeout is reported, display commands are blocked until restart. Leave it powered and report the status; do not repeatedly retry.</p><script src="/refresh-test.js"></script></html>)HTML";
constexpr char REFRESH_TEST_JS[] = R"JS(
'use strict';
const $=id=>document.getElementById(id),token=document.querySelector('meta[name="paper-token"]').content;
let last=null,sending=false;
function controls(){const blocked=sending||!last||last.busy||last.faulted;$('normal').disabled=blocked;$('fast').disabled=blocked||!last.baselineMs||!$('ack').checked;$('pattern').disabled=blocked;$('variant').disabled=blocked;}
async function poll(){try{const r=await fetch('/api/refresh-test');if(!r.ok)throw Error('Cannot read test status');last=await r.json();$('state').textContent=`${last.message}\nLast mode: ${last.mode}\nLast pattern: ${last.pattern} / variant ${last.variant}\nLast normal total: ${last.baselineMs? (last.baselineMs/1000).toFixed(2)+' s':'not measured'}\nLast accelerated total: ${last.fastMs?(last.fastMs/1000).toFixed(2)+' s':'not measured'}\nLast refresh BUSY interval: ${(last.busyMs/1000).toFixed(2)} s\nDefault timing restored: ${last.restored?'yes':'not confirmed'}\nReader/display request busy: ${last.busy?'yes':'no'}`;$('history').textContent=(last.history||[]).map(r=>`${r.pattern} ${r.variant} · ${r.mode} · ${(r.totalMs/1000).toFixed(2)} s total / ${(r.busyMs/1000).toFixed(2)} s BUSY`).join('\n')||'None this boot.';controls();}catch(e){$('message').textContent=e.message;last=null;controls();}}
async function run(mode){sending=true;controls();try{const r=await fetch('/api/refresh-test',{method:'POST',headers:{'X-Paper-Token':token},body:new URLSearchParams({mode,pattern:$('pattern').value,variant:$('variant').value,ack:$('ack').checked?'timing-experiment':''})});const data=await r.json();if(!r.ok)throw Error(data.error||'Test rejected');$('message').textContent='Queued. Watch the physical screen; do not switch off or reset.';await poll();}catch(e){$('message').textContent=e.message;}finally{sending=false;controls();}}
$('normal').onclick=()=>run('normal');$('fast').onclick=()=>run('accelerated');$('ack').onchange=controls;poll();setInterval(poll,1000);
)JS";
